server.port: 8081

spring:
  application:
    name: edu-social-media
  jpa:
    hibernate:
      ddl-auto: none
      # ddl-auto: create
      # ddl-auto: update
      # ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

