spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  issuer: ${JWT_ISSUER}
  signing_key_ac: ${JWT_SIGNING_KEY_AC}
  signing_key_rf: ${JWT_SIGNING_KEY_RF}
  expiration_ms_ac: ${JWT_EXPIRATION_MS_AC}
  expiration_ms_rf: ${JWT_EXPIRATION_MS_RF}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

geimini:
  api_key: ${GEIMINI_API_KEY}
  model: ${GEMINI_MODEL:gemini-2.5-flash}

edu_social_media:
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME}}

google:
  oauth:
    client_id: ${GOOGLE_OAUTH_CLIENT_ID}
    client_secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_OAUTH_REDIRECT_URI}
    frontend_redirect: ${GOOGLE_OAUTH_FRONTEND_REDIRECT}